### PR TITLE
Feat: Add documentation

### PR DESCRIPTION
**Pull request by joshuai96**
See: SovereignCloudStack/issues#610 & SovereignCloudStack/docs#207

### CODE REVIEW

**Comment by joshuai96** [comment]
@snkaupe could you add a little more documentation? This is mostly a placeholder, so i can add the web frontend to the docs.

**Comment by joshuai96** [comment]
This will be excluded from SovereignCloudStack/docs#207

**Comment by joshuai96** [comment]
Would be nice for SovereignCloudStack/issues#720

**Review by snkaupe — APPROVED** [review]
After a deep, thorough review of what I wrote just a few minutes ago, I agree with my former self and think this is ready for approval.

**Comment by joshuai96** [comment]
@joshmue for an external review.

**Review by joshmue — APPROVED** [review]

**Pull request merged**
