### PR TITLE
Rework containerization

### PR DESCRIPTION
**Pull request by joshuai96**
Minor changes to containerization

- Changes `Dockerfile` to `Containerfile` to be more general
  - Include `.container-ignore` to just copy wanted files.
  - Use official NGINX image
  - Include `LICENSE`, `README` and `3rdpartylicenses` into the image
- Change entrypoint
- Configure via environment variables with builtin `envsubst`
  - Config template `src/assets/config.tmpl.json`
  - Drop SCS prefix in environmental variables
- Configure NGINX in `nginx.conf`
  - Do not `try_files` with `=404` on Angular apps with router.
- Include `Makefile` with example container build and harbor push

### CODE REVIEW

**Comment by joshuai96** [comment]
@joshmue mentioned to me, that we should keep using `jq` for config values, as it ensures type safety.

**Comment by snkaupe** [comment]
Does that mean we shouldn't push this PR or can we go ahead?

**Comment by joshmue** [comment]
As long the inputs are strictly trusted and unlikely to contain any special characters, this should not be blocking.

**Review by snkaupe — APPROVED** [review]
All good now.

**Pull request merged**
